# Site settings
title: Власть Народа
email: sarhov@sarhov.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/vn_site"
url: "/" # the base hostname & protocol for your site

github_username:  sarhov

# Build settings
markdown: kramdown

top-nav:
- title: Новости  
  url: /news.html
- title: Статьи  
  url: /articles.html
- title: Аудио  
  url: /audio.html
- title: Видео  
  url: /vidoes.html
- title: Толковый словарь  
  url: /dictionary.html
- title: О проекте  
  url: /about_project.html
